# **Two types of data**

1. Numerical/Quantitive
    1. Discrete
       - Only takes countable values and can't be spllited.
       - Ex1:- No. of Students, No. of Apples
       - Ex2:- 1,2,3,4....
    2. Continuous
       - The data which can be splitted into smaller to smaller units.
       - Ex1:- Age Of person by dob(year, months, day etc.), Time(hrs, mins, secs etc)
       - Ex2:- 0.1, 0.2,0.3,1.4,1.6....
        <br><br>
2. Categorical/Qualitative
   1. Ordinal
      - Based on order or ranking.
      - Ex:- (good, better, best) or (small, big, tall)
   2. Nominal
      - Not based on order or ranking.
      - Ex:- Breeds of dog.
      
      

# **Terms in Stats**

1. Center of Data / Central Tendency-> Mean, Median, Mode
2. Spreadness of Data / Dispersion
3. Shape of Data
4. Outliers 

# Numpy

In [1]:
import numpy as np 

In [2]:
arr=np.array([23,45,67,34,67,89,23,67])
arr

array([23, 45, 67, 34, 67, 89, 23, 67])

In [3]:
arr.shape

(8,)

In [4]:
arr.size

8

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int32')

# Operations on Array

In [7]:
arr

array([23, 45, 67, 34, 67, 89, 23, 67])

In [8]:
arr+10

array([33, 55, 77, 44, 77, 99, 33, 77])

In [9]:
arr/10

array([2.3, 4.5, 6.7, 3.4, 6.7, 8.9, 2.3, 6.7])

In [11]:
arr          # since operations are immutable

array([23, 45, 67, 34, 67, 89, 23, 67])

In [12]:
arr+=10

In [13]:
arr

array([33, 55, 77, 44, 77, 99, 33, 77])

In [14]:
arr[0]

33

In [15]:
arr[-2]

33

In [16]:
arr[:5]

array([33, 55, 77, 44, 77])

In [17]:
arr

array([33, 55, 77, 44, 77, 99, 33, 77])

In [18]:
arr[1]=100

In [19]:
arr

array([ 33, 100,  77,  44,  77,  99,  33,  77])

In [20]:
arr[:4]

array([ 33, 100,  77,  44])

In [21]:
arr[:4]=0

In [22]:
arr

array([ 0,  0,  0,  0, 77, 99, 33, 77])

# Different ways for creating array

In [23]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [24]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
np.arange(10,21,0.5)                         # arange can work with float values but range can't

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [27]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [29]:
ages=np.random.randint(20,35,100)
ages

array([32, 22, 24, 21, 21, 29, 22, 31, 31, 34, 23, 34, 33, 28, 30, 24, 24,
       33, 28, 20, 34, 31, 28, 21, 26, 20, 21, 32, 24, 34, 33, 24, 26, 24,
       20, 22, 32, 29, 24, 33, 25, 21, 25, 33, 28, 28, 22, 33, 23, 29, 25,
       25, 26, 20, 30, 25, 32, 23, 26, 23, 25, 21, 20, 30, 31, 30, 23, 28,
       33, 30, 30, 29, 29, 24, 33, 33, 24, 20, 26, 21, 33, 31, 31, 27, 30,
       24, 21, 26, 34, 25, 33, 25, 24, 28, 28, 30, 23, 26, 29, 25])

# Center Of data
1. Mean
2. Median
3. Mode

In [30]:
sum(ages)/len(ages)

26.97

In [31]:
ages.mean()

26.97

In [32]:
np.mean(ages)

26.97

In [33]:
np.median(ages)

26.0