In [3]:
import numpy as np

In [4]:
ages=np.random.randint(20,35,100)
ages

array([29, 22, 30, 22, 30, 34, 24, 32, 32, 26, 27, 22, 29, 21, 34, 32, 27,
       25, 27, 25, 22, 21, 33, 32, 26, 22, 33, 22, 29, 20, 33, 28, 27, 22,
       34, 21, 29, 29, 32, 23, 25, 25, 21, 20, 26, 27, 22, 25, 20, 20, 21,
       22, 26, 20, 25, 33, 29, 22, 20, 30, 27, 34, 28, 28, 30, 25, 23, 24,
       27, 21, 28, 25, 31, 33, 25, 24, 30, 28, 25, 33, 29, 34, 32, 26, 23,
       32, 28, 20, 21, 27, 23, 27, 22, 20, 21, 29, 31, 21, 30, 33])

### Mean, Median, Mode
                Mean-> Avg of values. We identify the approximate maximum repeated value
                Median-> Avg of positions
                Mode-> The data with high frequency is mode
                

In [5]:
sum(ages)/len(ages)

26.45

In [6]:
ages.mean()

26.45

In [7]:
np.mean(ages)

26.45

In [8]:
np.median(ages)

26.5

In [9]:
ages

array([29, 22, 30, 22, 30, 34, 24, 32, 32, 26, 27, 22, 29, 21, 34, 32, 27,
       25, 27, 25, 22, 21, 33, 32, 26, 22, 33, 22, 29, 20, 33, 28, 27, 22,
       34, 21, 29, 29, 32, 23, 25, 25, 21, 20, 26, 27, 22, 25, 20, 20, 21,
       22, 26, 20, 25, 33, 29, 22, 20, 30, 27, 34, 28, 28, 30, 25, 23, 24,
       27, 21, 28, 25, 31, 33, 25, 24, 30, 28, 25, 33, 29, 34, 32, 26, 23,
       32, 28, 20, 21, 27, 23, 27, 22, 20, 21, 29, 31, 21, 30, 33])

In [10]:
new_ages=np.random.randint(80,91,10)
new_ages

array([90, 84, 87, 84, 83, 81, 80, 88, 90, 89])

In [14]:
new_arr=np.append(ages, new_ages)       # we add extreme high values. Since outliers are extreme high or low values
new_arr

array([29, 22, 30, 22, 30, 34, 24, 32, 32, 26, 27, 22, 29, 21, 34, 32, 27,
       25, 27, 25, 22, 21, 33, 32, 26, 22, 33, 22, 29, 20, 33, 28, 27, 22,
       34, 21, 29, 29, 32, 23, 25, 25, 21, 20, 26, 27, 22, 25, 20, 20, 21,
       22, 26, 20, 25, 33, 29, 22, 20, 30, 27, 34, 28, 28, 30, 25, 23, 24,
       27, 21, 28, 25, 31, 33, 25, 24, 30, 28, 25, 33, 29, 34, 32, 26, 23,
       32, 28, 20, 21, 27, 23, 27, 22, 20, 21, 29, 31, 21, 30, 33, 90, 84,
       87, 84, 83, 81, 80, 88, 90, 89])

In [16]:
np.mean(new_arr)      # here mean is affected by the outliers

31.827272727272728

In [17]:
np.median(new_arr)

27.0

In [19]:
country=np.random.choice(['india','usa','china','aus'],100)
country

array(['usa', 'china', 'india', 'usa', 'usa', 'china', 'india', 'india',
       'aus', 'aus', 'india', 'china', 'india', 'china', 'india', 'china',
       'china', 'india', 'india', 'china', 'aus', 'usa', 'usa', 'aus',
       'china', 'aus', 'china', 'aus', 'aus', 'aus', 'aus', 'india',
       'usa', 'india', 'usa', 'usa', 'aus', 'india', 'usa', 'aus',
       'china', 'india', 'india', 'usa', 'aus', 'china', 'aus', 'china',
       'india', 'aus', 'usa', 'aus', 'india', 'usa', 'usa', 'aus', 'usa',
       'aus', 'india', 'india', 'usa', 'aus', 'aus', 'usa', 'usa', 'aus',
       'usa', 'usa', 'aus', 'aus', 'usa', 'india', 'aus', 'usa', 'india',
       'aus', 'china', 'aus', 'usa', 'china', 'usa', 'aus', 'china',
       'usa', 'china', 'usa', 'usa', 'aus', 'usa', 'china', 'usa',
       'china', 'india', 'usa', 'usa', 'aus', 'china', 'china', 'india',
       'usa'], dtype='<U5')

In [20]:
import statistics

In [21]:
statistics.mode(country)

'usa'

In [22]:
d=dict()
for i in country: 
    if i in d: 
        d[i]+=1
    else: 
        d[i]=1

In [23]:
d

{'usa': 31, 'china': 20, 'india': 21, 'aus': 28}

In [27]:
d.values()

dict_values([31, 20, 21, 28])

In [25]:
m=max(d.values())
m

31

In [26]:
d.items()

dict_items([('usa', 31), ('china', 20), ('india', 21), ('aus', 28)])

In [28]:
for key, value in d.items(): 
    if value==m: 
        print(key)

usa


# Spreadness Of Data
1. range-> when we covers the speardness using range then it will covers the outliers 
2. standard deviation-> the average distance of all datapoints from mean.
3. variance
4. quantiles, IQR

In [30]:
mean=np.mean(ages)
mean

26.45

In [33]:
print([(mean-age)for age in ages])

[-2.5500000000000007, 4.449999999999999, -3.5500000000000007, 4.449999999999999, -3.5500000000000007, -7.550000000000001, 2.4499999999999993, -5.550000000000001, -5.550000000000001, 0.4499999999999993, -0.5500000000000007, 4.449999999999999, -2.5500000000000007, 5.449999999999999, -7.550000000000001, -5.550000000000001, -0.5500000000000007, 1.4499999999999993, -0.5500000000000007, 1.4499999999999993, 4.449999999999999, 5.449999999999999, -6.550000000000001, -5.550000000000001, 0.4499999999999993, 4.449999999999999, -6.550000000000001, 4.449999999999999, -2.5500000000000007, 6.449999999999999, -6.550000000000001, -1.5500000000000007, -0.5500000000000007, 4.449999999999999, -7.550000000000001, 5.449999999999999, -2.5500000000000007, -2.5500000000000007, -5.550000000000001, 3.4499999999999993, 1.4499999999999993, 1.4499999999999993, 5.449999999999999, 6.449999999999999, 0.4499999999999993, -0.5500000000000007, 4.449999999999999, 1.4499999999999993, 6.449999999999999, 6.449999999999999, 5.

In [34]:
d=[abs(mean-age)for age in ages]
d

[2.5500000000000007,
 4.449999999999999,
 3.5500000000000007,
 4.449999999999999,
 3.5500000000000007,
 7.550000000000001,
 2.4499999999999993,
 5.550000000000001,
 5.550000000000001,
 0.4499999999999993,
 0.5500000000000007,
 4.449999999999999,
 2.5500000000000007,
 5.449999999999999,
 7.550000000000001,
 5.550000000000001,
 0.5500000000000007,
 1.4499999999999993,
 0.5500000000000007,
 1.4499999999999993,
 4.449999999999999,
 5.449999999999999,
 6.550000000000001,
 5.550000000000001,
 0.4499999999999993,
 4.449999999999999,
 6.550000000000001,
 4.449999999999999,
 2.5500000000000007,
 6.449999999999999,
 6.550000000000001,
 1.5500000000000007,
 0.5500000000000007,
 4.449999999999999,
 7.550000000000001,
 5.449999999999999,
 2.5500000000000007,
 2.5500000000000007,
 5.550000000000001,
 3.4499999999999993,
 1.4499999999999993,
 1.4499999999999993,
 5.449999999999999,
 6.449999999999999,
 0.4499999999999993,
 0.5500000000000007,
 4.449999999999999,
 1.4499999999999993,
 6.44999999999999

In [36]:
np.mean(d)

3.75

In [37]:
np.std(ages)

4.350574674683794

In [38]:
np.var(ages)

18.9275

In [39]:
ages

array([29, 22, 30, 22, 30, 34, 24, 32, 32, 26, 27, 22, 29, 21, 34, 32, 27,
       25, 27, 25, 22, 21, 33, 32, 26, 22, 33, 22, 29, 20, 33, 28, 27, 22,
       34, 21, 29, 29, 32, 23, 25, 25, 21, 20, 26, 27, 22, 25, 20, 20, 21,
       22, 26, 20, 25, 33, 29, 22, 20, 30, 27, 34, 28, 28, 30, 25, 23, 24,
       27, 21, 28, 25, 31, 33, 25, 24, 30, 28, 25, 33, 29, 34, 32, 26, 23,
       32, 28, 20, 21, 27, 23, 27, 22, 20, 21, 29, 31, 21, 30, 33])

In [40]:
ages.size

100

In [48]:
ages.ndim

1

In [49]:
ages.shape

(100,)

In [55]:
arr=np.array([0,0,0,0,77,99,33,77])
arr

array([ 0,  0,  0,  0, 77, 99, 33, 77])

In [56]:
arr[0]

0

In [57]:
arr[[3,7,2]]

array([ 0, 77,  0])

In [60]:
arr[[False, True, False, True, False, False, True, True]]

array([ 0,  0, 33, 77])

In [61]:
arr

array([ 0,  0,  0,  0, 77, 99, 33, 77])

In [62]:
arr > 70 

array([False, False, False, False,  True,  True, False,  True])

In [63]:
arr[arr>70]

array([77, 99, 77])

In [64]:
np.arange(20,51,5)

array([20, 25, 30, 35, 40, 45, 50])

In [66]:
np.arange(-5,5.5,.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [68]:
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [69]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [70]:
np.linspace(0,1,2)

array([0., 1.])

In [72]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [71]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [73]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Multidimensional Arrays

In [81]:
arr_1d=np.random.randint(20,51,100)
arr_1d

array([21, 30, 42, 31, 35, 30, 36, 24, 46, 47, 42, 46, 49, 25, 27, 26, 41,
       33, 44, 49, 50, 32, 46, 43, 37, 38, 28, 27, 41, 29, 39, 28, 39, 31,
       23, 34, 21, 23, 44, 43, 36, 28, 46, 38, 36, 50, 41, 47, 49, 26, 26,
       24, 37, 30, 31, 28, 30, 48, 31, 39, 37, 41, 25, 23, 31, 40, 34, 37,
       32, 36, 38, 22, 29, 44, 29, 37, 48, 34, 33, 47, 47, 21, 34, 38, 33,
       29, 38, 50, 49, 34, 24, 42, 50, 32, 28, 24, 32, 26, 44, 24])

In [82]:
arr_2d=arr_1d.reshape(10,10)
arr_2d

array([[21, 30, 42, 31, 35, 30, 36, 24, 46, 47],
       [42, 46, 49, 25, 27, 26, 41, 33, 44, 49],
       [50, 32, 46, 43, 37, 38, 28, 27, 41, 29],
       [39, 28, 39, 31, 23, 34, 21, 23, 44, 43],
       [36, 28, 46, 38, 36, 50, 41, 47, 49, 26],
       [26, 24, 37, 30, 31, 28, 30, 48, 31, 39],
       [37, 41, 25, 23, 31, 40, 34, 37, 32, 36],
       [38, 22, 29, 44, 29, 37, 48, 34, 33, 47],
       [47, 21, 34, 38, 33, 29, 38, 50, 49, 34],
       [24, 42, 50, 32, 28, 24, 32, 26, 44, 24]])

In [83]:
arr_3d=arr_1d.reshape(2,10,5)
arr_3d

array([[[21, 30, 42, 31, 35],
        [30, 36, 24, 46, 47],
        [42, 46, 49, 25, 27],
        [26, 41, 33, 44, 49],
        [50, 32, 46, 43, 37],
        [38, 28, 27, 41, 29],
        [39, 28, 39, 31, 23],
        [34, 21, 23, 44, 43],
        [36, 28, 46, 38, 36],
        [50, 41, 47, 49, 26]],

       [[26, 24, 37, 30, 31],
        [28, 30, 48, 31, 39],
        [37, 41, 25, 23, 31],
        [40, 34, 37, 32, 36],
        [38, 22, 29, 44, 29],
        [37, 48, 34, 33, 47],
        [47, 21, 34, 38, 33],
        [29, 38, 50, 49, 34],
        [24, 42, 50, 32, 28],
        [24, 32, 26, 44, 24]]])

In [84]:
np.random.randint(20,35,100)

array([23, 23, 31, 32, 27, 26, 27, 23, 27, 26, 29, 31, 31, 28, 33, 22, 22,
       30, 24, 29, 28, 33, 29, 31, 26, 21, 20, 34, 27, 31, 32, 20, 30, 32,
       30, 34, 24, 29, 22, 26, 28, 23, 27, 25, 30, 24, 31, 22, 29, 24, 26,
       33, 32, 29, 31, 26, 30, 27, 20, 20, 24, 27, 33, 28, 26, 25, 26, 23,
       33, 34, 31, 25, 27, 26, 26, 24, 30, 33, 32, 23, 34, 26, 28, 29, 28,
       25, 27, 20, 34, 26, 20, 26, 27, 27, 24, 27, 26, 23, 23, 31])

In [85]:
np.random.randint(20,35,(10,4))

array([[29, 20, 28, 31],
       [21, 32, 25, 22],
       [32, 30, 26, 22],
       [27, 30, 27, 22],
       [25, 33, 26, 23],
       [29, 20, 22, 23],
       [31, 27, 20, 28],
       [24, 20, 21, 30],
       [20, 33, 24, 32],
       [29, 20, 21, 24]])

In [86]:
np.random.randint(20,35,(5,4,5))

array([[[31, 27, 23, 25, 28],
        [28, 25, 21, 32, 33],
        [34, 28, 21, 29, 26],
        [20, 34, 32, 25, 21]],

       [[33, 33, 30, 29, 34],
        [31, 25, 22, 23, 29],
        [27, 21, 20, 33, 20],
        [31, 22, 31, 31, 30]],

       [[21, 30, 24, 30, 32],
        [34, 30, 23, 20, 34],
        [23, 31, 34, 21, 33],
        [23, 30, 25, 21, 26]],

       [[31, 30, 24, 23, 24],
        [34, 27, 27, 33, 31],
        [30, 33, 30, 29, 27],
        [31, 20, 33, 32, 30]],

       [[21, 25, 29, 21, 25],
        [34, 21, 20, 34, 29],
        [24, 32, 30, 30, 26],
        [31, 31, 22, 29, 20]]])

In [97]:
arr_2d=np.random.randint(20,50,(4,5))
arr_2d

array([[20, 43, 33, 26, 36],
       [47, 22, 44, 33, 37],
       [24, 31, 24, 35, 46],
       [41, 23, 34, 46, 25]])

In [98]:
arr_2d[1]

array([47, 22, 44, 33, 37])

In [99]:
arr_2d[1][3]

33

In [100]:
arr_2d[1,3]

33

In [101]:
arr_2d[1,-2]

33

In [102]:
arr_2d[1:3, 1:2]

array([[22],
       [31]])

In [103]:
arr_2d[1:3,1:3]    

array([[22, 44],
       [31, 24]])

In [104]:
arr_2d[1:3,2:4]    

array([[44, 33],
       [24, 35]])

In [105]:
arr_3d=np.random.randint(20,51,(3,3,4))
arr_3d

array([[[30, 45, 20, 25],
        [20, 21, 49, 31],
        [36, 20, 40, 27]],

       [[45, 45, 21, 43],
        [49, 30, 20, 22],
        [29, 50, 42, 24]],

       [[38, 38, 24, 20],
        [42, 34, 49, 30],
        [27, 45, 44, 22]]])

In [106]:
arr_3d.size

36

In [107]:
arr_3d.shape

(3, 3, 4)

In [108]:
arr_3d.ndim

3

In [109]:
arr_3d

array([[[30, 45, 20, 25],
        [20, 21, 49, 31],
        [36, 20, 40, 27]],

       [[45, 45, 21, 43],
        [49, 30, 20, 22],
        [29, 50, 42, 24]],

       [[38, 38, 24, 20],
        [42, 34, 49, 30],
        [27, 45, 44, 22]]])

In [110]:
arr_3d[1]

array([[45, 45, 21, 43],
       [49, 30, 20, 22],
       [29, 50, 42, 24]])

In [113]:
arr_3d[1,-1,-2]

42

In [114]:
arr_3d[::2,::2,::2]

array([[[30, 20],
        [36, 40]],

       [[38, 24],
        [27, 44]]])