In [1]:
import numpy as np

In [4]:
arr=np.array([21,5,2,67,34,89,34,98])
arr

array([21,  5,  2, 67, 34, 89, 34, 98])

In [5]:
arr.argsort()

array([2, 1, 0, 4, 6, 3, 5, 7], dtype=int64)

In [6]:
arr[arr.argsort()]

array([ 2,  5, 21, 34, 34, 67, 89, 98])

In [11]:
# let colums are like that cost_price, selling_price, quantity. Find out the profit
arr_2d=np.array([
    [5000,5600,9],
    [4300,5000,6],
    [2200,3000,8],
    [2900,4500,10]
])

In [17]:
arr_2d

array([[5000, 5600,    9],
       [4300, 5000,    6],
       [2200, 3000,    8],
       [2900, 4500,   10]])

In [22]:
profit=arr_2d[:,2]*(arr_2d[:,1]-arr_2d[:,0])
profit

array([ 5400,  4200,  6400, 16000])

In [24]:
total_profit=profit.sum()
total_profit

32000

In [30]:
%%writefile data.csv
price,selling_price,quantity
5000,5600,9
4300,5000,6
2200,3000,8
2900,4500,10

Overwriting data.csv


In [32]:
np.genfromtxt('data.csv',delimiter=',',skip_header=1)

array([[5000., 5600.,    9.],
       [4300., 5000.,    6.],
       [2200., 3000.,    8.],
       [2900., 4500.,   10.]])

In [33]:
np.full((5,4), fill_value=np.round(np.pi,2))

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [39]:
arr_2d=np.arange(1,21).reshape(4,5)

In [40]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [45]:
arr_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
arr_2d.flatten(order='F')

array([ 1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,  9, 14, 19,  5,
       10, 15, 20])

In [47]:
arr_2d.flatten(order='F').reshape(4,5)

array([[ 1,  6, 11, 16,  2],
       [ 7, 12, 17,  3,  8],
       [13, 18,  4,  9, 14],
       [19,  5, 10, 15, 20]])

In [48]:
arr_2d.flatten(order='F').reshape(4,5, order='F')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])