In [ ]:
pip install numpy

In [1]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [4]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
arr.size

10

In [8]:
arr.ndim

1

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr.shape

(10,)

In [11]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
arr[0]

10

In [13]:
arr[-1]

100

In [14]:
arr[:4]

array([10, 20, 30, 40])

In [17]:
ls = [23, 45, 12, 5, 46, 21, 36, 57, 323, 546, 768]

In [18]:
ls

[23, 45, 12, 5, 46, 21, 36, 57, 323, 546, 768]

In [19]:
ls[0]

23

In [20]:
ls[:3]

[23, 45, 12]

In [21]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
ls

[23, 45, 12, 5, 46, 21, 36, 57, 323, 546, 768]

In [23]:
ls[0] = 100

In [24]:
ls

[100, 45, 12, 5, 46, 21, 36, 57, 323, 546, 768]

In [25]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [26]:
arr[0]

10

In [27]:
arr[0] = 200

In [28]:
arr

array([200,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
arr[:4] = 1

In [30]:

arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [31]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [32]:
arr[3:8:2]

array([ 1, 60, 80])

In [34]:
arr[[0,3,7,2]]

array([ 1,  1, 80,  1])

In [35]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [36]:
arr[[True, False, False, False, False, False, False, False, True, False]]

array([ 1, 90])

In [37]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [39]:
arr + 10

array([ 11,  11,  11,  11,  60,  70,  80,  90, 100, 110])

In [38]:
ls

[100, 45, 12, 5, 46, 21, 36, 57, 323, 546, 768]

In [40]:
ls + 10

TypeError: can only concatenate list (not "int") to list

In [41]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [42]:
arr / 10

array([ 0.1,  0.1,  0.1,  0.1,  5. ,  6. ,  7. ,  8. ,  9. , 10. ])

In [43]:
arr ** 2

array([    1,     1,     1,     1,  2500,  3600,  4900,  6400,  8100,
       10000])

In [44]:
arr * 5

array([  5,   5,   5,   5, 250, 300, 350, 400, 450, 500])

In [45]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [46]:
arr > 5

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[arr > 5]

array([ 50,  60,  70,  80,  90, 100])

In [48]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [49]:
arr.sum()

454

In [50]:
arr.min()

1

In [51]:
arr.max()

100

In [52]:
arr.mean()

45.4

In [53]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [54]:
np.median(arr)

55.0

In [55]:
arr.sort()

In [56]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [57]:
arr1 = np.array([34,56,23,67,34,78,89,34,78])
arr1

array([34, 56, 23, 67, 34, 78, 89, 34, 78])

In [58]:
arr1.sort()

In [59]:
arr1

array([23, 34, 34, 34, 56, 67, 78, 78, 89])

In [61]:
arr1

array([23, 34, 34, 34, 56, 67, 78, 78, 89])

In [62]:
arr1.argmin()

0

In [63]:
arr1.argmax()

8

In [64]:
ar = np.array([21,5,2,67,34,89,34,98])

In [65]:
ar.argsort()

array([2, 1, 0, 4, 6, 3, 5, 7], dtype=int64)

In [67]:
ar[[3,6,7]]

array([67, 34, 98])

In [68]:
ar[ar.argsort()]

array([ 2,  5, 21, 34, 34, 67, 89, 98])

## 2 D array

            collection of 1-D array

In [70]:
arr_2d = np.array([
    [10,20,30],
    [45,67,34],
    [76,89,67]
])
arr_2d

array([[10, 20, 30],
       [45, 67, 34],
       [76, 89, 67]])

In [71]:
arr_2d.shape

(3, 3)

In [72]:
arr_2d.size

9

In [73]:
arr_2d.ndim

2

In [74]:
arr_2d.dtype

dtype('int32')

### indexing & slicing on 2-D array

                syntax:

                        indexing:
                                    arr[row_index, col_index]

                        slicing:
                                    arr[row_slicing, col_slicing]

In [75]:
arr_2d

array([[10, 20, 30],
       [45, 67, 34],
       [76, 89, 67]])

In [76]:
len(arr_2d)

3

In [77]:
arr_2d.size

9

In [78]:
arr_2d

array([[10, 20, 30],
       [45, 67, 34],
       [76, 89, 67]])

In [79]:
arr_2d[0]

array([10, 20, 30])

In [80]:
arr_2d[1]

array([45, 67, 34])

In [81]:
arr_2d

array([[10, 20, 30],
       [45, 67, 34],
       [76, 89, 67]])

In [82]:
arr_2d[1]

array([45, 67, 34])

In [83]:
arr_2d[1][2]


34

In [84]:
arr_2d[1,2]

34

In [85]:
arr_2d

array([[10, 20, 30],
       [45, 67, 34],
       [76, 89, 67]])

In [86]:
arr_2d + 10

array([[20, 30, 40],
       [55, 77, 44],
       [86, 99, 77]])

In [87]:
arr_2d / 10

array([[1. , 2. , 3. ],
       [4.5, 6.7, 3.4],
       [7.6, 8.9, 6.7]])

In [88]:
arr_2d // 10


array([[1, 2, 3],
       [4, 6, 3],
       [7, 8, 6]], dtype=int32)

In [89]:
arr_2d

array([[10, 20, 30],
       [45, 67, 34],
       [76, 89, 67]])

In [90]:
arr_2d > 45

array([[False, False, False],
       [False,  True, False],
       [ True,  True,  True]])

In [91]:
arr_2d[arr_2d > 45]

array([67, 76, 89, 67])

In [92]:
arr_2d

array([[10, 20, 30],
       [45, 67, 34],
       [76, 89, 67]])

In [93]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [94]:
arr1

array([23, 34, 34, 34, 56, 67, 78, 78, 89])

In [95]:
arr.__len__()

10

In [96]:
arr1.__len__()

9

In [97]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [98]:
arr1 = np.array([23,56,23,67,34,67,34,78,23,67])
arr1

array([23, 56, 23, 67, 34, 67, 34, 78, 23, 67])

In [99]:
arr

array([  1,   1,   1,   1,  50,  60,  70,  80,  90, 100])

In [100]:
arr + arr1

array([ 24,  57,  24,  68,  84, 127, 104, 158, 113, 167])

In [101]:
arr / arr1

array([0.04347826, 0.01785714, 0.04347826, 0.01492537, 1.47058824,
       0.89552239, 2.05882353, 1.02564103, 3.91304348, 1.49253731])

In [102]:
arr // arr1


array([0, 0, 0, 0, 1, 0, 2, 1, 3, 1])

In [1]:
import numpy as np

    np.array()
    np.arange()
    np.linspace()
    np.random.randint()
    np.random.randn()
    np.random.normal()
    np.random.uniform()
    np.ones()
    np.zeros()
    np.eye()
    np.full()
    np.empty()
    

In [2]:
np.arange(1, 11, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.arange(-5, 10, 2)

array([-5, -3, -1,  1,  3,  5,  7,  9])

In [4]:
range(-5 , 10)

range(-5, 10)

In [5]:
range(1.1 , 2.5)


TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(0, 1.1)

array([0., 1.])

In [7]:
np.arange(0, 1.9)


array([0., 1.])

In [10]:
np.arange(0, 1.1, 0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [11]:
np.arange(1, 2.1, 0.01)

array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
       1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99, 2.  , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08, 2.09])

In [12]:
np.arange(10, 101, -10)

array([], dtype=int32)

In [13]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [14]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [16]:
np.linspace(0, 1, 1000)


array([0.        , 0.001001  , 0.002002  , 0.003003  , 0.004004  ,
       0.00500501, 0.00600601, 0.00700701, 0.00800801, 0.00900901,
       0.01001001, 0.01101101, 0.01201201, 0.01301301, 0.01401401,
       0.01501502, 0.01601602, 0.01701702, 0.01801802, 0.01901902,
       0.02002002, 0.02102102, 0.02202202, 0.02302302, 0.02402402,
       0.02502503, 0.02602603, 0.02702703, 0.02802803, 0.02902903,
       0.03003003, 0.03103103, 0.03203203, 0.03303303, 0.03403403,
       0.03503504, 0.03603604, 0.03703704, 0.03803804, 0.03903904,
       0.04004004, 0.04104104, 0.04204204, 0.04304304, 0.04404404,
       0.04504505, 0.04604605, 0.04704705, 0.04804805, 0.04904905,
       0.05005005, 0.05105105, 0.05205205, 0.05305305, 0.05405405,
       0.05505506, 0.05605606, 0.05705706, 0.05805806, 0.05905906,
       0.06006006, 0.06106106, 0.06206206, 0.06306306, 0.06406406,
       0.06506507, 0.06606607, 0.06706707, 0.06806807, 0.06906907,
       0.07007007, 0.07107107, 0.07207207, 0.07307307, 0.07407

In [17]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
arr_1d = np.arange(1, 21)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
arr_1d.shape

(20,)

In [22]:
arr_2d = arr_1d.reshape(4,5)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
arr_2d[2, -2]

14

In [24]:
arr_2d[1:3, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [25]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
arr_2d[::-1, ::2]

array([[16, 18, 20],
       [11, 13, 15],
       [ 6,  8, 10],
       [ 1,  3,  5]])

In [27]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
arr_2d[:, 0]

array([ 1,  6, 11, 16])

In [35]:
arr_2d[:, 0] = 0
arr_2d[:, -1] = 0
arr_2d[0, :] = 0
arr_2d[-1, :] = 0

In [36]:
arr_2d

array([[ 0,  0,  0,  0,  0],
       [ 0,  7,  8,  9,  0],
       [ 0, 12, 13, 14,  0],
       [ 0,  0,  0,  0,  0]])

In [38]:
arr1 = np.arange(1,21).reshape(4,5)
arr2 = np.arange(10, 30).reshape(4,5)

In [39]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
arr2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [41]:
arr1 + arr2

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [42]:
arr1 / 10

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ]])

In [43]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286],
       [0.4       , 0.4375    , 0.47058824, 0.5       , 0.52631579],
       [0.55      , 0.57142857, 0.59090909, 0.60869565, 0.625     ],
       [0.64      , 0.65384615, 0.66666667, 0.67857143, 0.68965517]])

In [44]:
arr1 // arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
arr = np.arange(1, 20)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [47]:
arr.mean()

10.0

In [48]:
arr.sum()

190

In [49]:
arr.min()

1

In [50]:
arr.max()

19

In [51]:
data = np.random.randint(30, 50, 9)
data

array([37, 30, 39, 42, 32, 41, 33, 35, 43])

In [54]:
data = np.random.randint(30, 50, (3,3))
data

array([[32, 39, 35],
       [36, 42, 33],
       [48, 45, 46]])

In [55]:
data.sum()

356

In [56]:
data.sum(axis=1)

array([106, 111, 139])

In [57]:
32+39+35

106

In [58]:
data.sum(axis=1) / 3


array([35.33333333, 37.        , 46.33333333])

In [59]:
data.mean()

39.55555555555556

In [60]:
data.mean(axis=1)


array([35.33333333, 37.        , 46.33333333])

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [62]:
arr.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

In [63]:
arr.cumprod()

array([         1,          2,          6,         24,        120,
              720,       5040,      40320,     362880,    3628800,
         39916800,  479001600, 1932053504, 1278945280, 2004310016,
       2004189184, -288522240, -898433024,  109641728])

In [64]:
import numpy as np

In [65]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20 ]])

In [66]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [68]:
arr[2:, 3]

array([14, 19])

### 3-D array

                collection of 2-D array

In [86]:
arr_3d = np.array([
    [
        [10,20,30],
        [60,70,80]
    ],
    [
        [11,22,33],
        [44,55,66]
    ]
])

In [87]:
arr_3d

array([[[10, 20, 30],
        [60, 70, 80]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [88]:
arr_3d[0]

array([[10, 20, 30],
       [60, 70, 80]])

In [89]:
arr_3d[0, 1, 1]

70

In [71]:
arr_3d.size

12

In [72]:
arr_3d.shape

(2, 2, 3)

In [73]:
arr_3d.ndim

3

In [74]:
arr_3d.dtype

dtype('int32')

In [75]:
arr = np.arange(1, 101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [76]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [77]:
arr.reshape(20, 5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [78]:
arr.reshape(10, 10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [79]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [81]:
arr.reshape(2,10,5)

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

    indexing:

                arr[record_index, row_index, col_index]

    slicing:
                arr[record_slicing, row_slicing, col_slicing]

In [90]:
arr_3d = arr.reshape(5, 2, 10)
arr_3d

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [92]:
arr_3d[2]

array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [91]:
arr_3d[::2, :1, 2:7]

array([[[ 3,  4,  5,  6,  7]],

       [[43, 44, 45, 46, 47]],

       [[83, 84, 85, 86, 87]]])

In [93]:
arr_2d = np.array([
    [5000, 5600, 9],
    [4300, 5000, 6],
    [2200, 3000, 8],
    [2900, 4500, 10]
])

In [94]:
arr_2d

array([[5000, 5600,    9],
       [4300, 5000,    6],
       [2200, 3000,    8],
       [2900, 4500,   10]])

In [98]:
((arr_2d[:, 1] - arr_2d[:, 0]) * arr_2d[:, -1]).sum()

32000

In [100]:
%%writefile sell.csv
price,selling_price,quantity
5000, 5600, 9
4300, 5000, 6
2200, 3000, 8
2900, 4500, 10

Writing sell.csv


In [105]:
np.genfromtxt('sell.csv', delimiter=',', skip_header=1)


array([[5000., 5600.,    9.],
       [4300., 5000.,    6.],
       [2200., 3000.,    8.],
       [2900., 4500.,   10.]])

In [103]:
np.genfromtxt('sell.csv', dtype='int', delimiter=',', skip_header=1)

array([[5000, 5600,    9],
       [4300, 5000,    6],
       [2200, 3000,    8],
       [2900, 4500,   10]])

In [106]:
np.genfromtxt('sell.csv', dtype='int', delimiter=',', skip_header=1, skip_footer=2)

array([[5000, 5600,    9],
       [4300, 5000,    6]])

In [108]:
data

array([[32, 39, 35],
       [36, 42, 33],
       [48, 45, 46]])

In [109]:
data.flatten()

array([32, 39, 35, 36, 42, 33, 48, 45, 46])

In [110]:
arr_3d

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [111]:
arr_3d.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [112]:
data

array([[32, 39, 35],
       [36, 42, 33],
       [48, 45, 46]])

In [113]:
data.flatten()

array([32, 39, 35, 36, 42, 33, 48, 45, 46])

In [114]:
data.flatten().reshape(3,3)


array([[32, 39, 35],
       [36, 42, 33],
       [48, 45, 46]])

In [115]:
data

array([[32, 39, 35],
       [36, 42, 33],
       [48, 45, 46]])

In [116]:
data.flatten(order='F')

array([32, 36, 48, 39, 42, 45, 35, 33, 46])

In [118]:
data.flatten(order='F').reshape(3,3)


array([[32, 36, 48],
       [39, 42, 45],
       [35, 33, 46]])

In [119]:
data.flatten(order='F').reshape((3,3), order='F')


array([[32, 39, 35],
       [36, 42, 33],
       [48, 45, 46]])